function NewAirlineOnRoute = CF_NewAirlineOnRoute...
                            (AL_label, Route_label, data_info, sampler, lower, upper)
% This is a counterfactural experimented designed to test when adding an
% airline onto a route, whether this new player would compete with old ones
%   Specifically, we would like to add AL_name onto Route_Name
    NewAirlineOnRoute = struct; 
    mu = sampler.mu;
    phi = sampler.phi;
    level = sampler.level;
    factor = sampler.factor;
    factor_xi = sampler.factor_xi(:,3);
    [iter, n_cluster] = size(mu);
       
    levels_in_factors = data_info.levels_in_factors;
    sub = levels_in_factors;
    sub(2) = levels_in_factors(1)+levels_in_factors(2);
    sub(3) = sub(2) + levels_in_factors(3);
    indep = data_info.indep;
    %% Threshold to compare
    tail_threshold = [    0,    12, 15.5,    24, 32.2,   48, 63.2,    72, 82.5,  99.3]; % 1-cdf
    tail_perc =      [0.798, 0.888,  0.9, 0.938, 0.95, 0.97, 0.98, 0.987, 0.99, 0.995];
    %quantile(data_info.dep, [0.005,  0.01,  0.02,  0.05, 0.049,   0.1,
    %0.15]);
    head_threshold = [-65.4, -51.5, -39.4, -24.9,   -24, -16.6,  -12]; % cdf
    head_perc =      [0.005,  0.01,  0.02,  0.05, 0.054,   0.1, 0.15];
    %% Data manupulation -- calculate the orignal airlines on this route
    % find airline-route combinations with certain route specified
    mid = indep(indep(:,2)==Route_label,:);
    airlines = unique(mid, 'rows');
    n_airline = size(airlines,1);
    for i=1:n_airline+1
        if i <= n_airline
        alpha = repmat(factor(:,i)...
                       +factor(:,sub(1)+Route_label)...
                       +factor(:,sub(2)+airlines(i,3)),...
                       1, n_cluster-1)...
                +level;
        elseif i == n_airline+1
        alpha = repmat(factor(:,AL_label)...
                       +factor(:,sub(1)+Route_label)...
                       +normrnd(0,1./sqrt(factor_xi),[iter,1]),...
                       1, n_cluster-1)...
                +level;
        end
        t = lower:1:upper;
        t_length = length(t);               
        omega = zeros(iter,n_cluster);
        omega(:,1) = normcdf(alpha(:,1));       
        q = repmat(omega(:,1),1,t_length).*...
            normpdf(repmat(t,iter,1)...
                    ,repmat(mu(:,1),1,t_length)...
                    ,1./sqrt(repmat(phi(:,1),1,t_length)));       
        head_prob = repmat(omega(:,1),1,length(head_threshold)).*...
                    normcdf(repmat(head_threshold,iter,1)...
                            ,repmat(mu(:,1),1,length(head_threshold))...
                            ,1./sqrt(repmat(phi(:,1),1,length(head_threshold))));       
        tail_prob = repmat(omega(:,1),1,length(tail_threshold)).*...
                    (1-normcdf(repmat(tail_threshold,iter,1)...
                                ,repmat(mu(:,1),1,length(tail_threshold))...
                                ,1./sqrt(repmat(phi(:,1),1,length(tail_threshold)))));       
        average = omega(:,1).*mu(:,1);      
        for j=2:n_cluster-1
            omega(:,j) = (1-sum(omega(:,1:j-1),2)).*normcdf(alpha(:,j));            
            q = q+repmat(omega(:,j),1,t_length)...
                .*normpdf(repmat(t,iter,1),...
                          repmat(mu(:,j),1,t_length),...
                          1./sqrt(repmat(phi(:,j),1,t_length)));           
            head_prob = head_prob+repmat(omega(:,j),1,length(head_threshold)).*...
                            normcdf(repmat(head_threshold,iter,1)...
                                   ,repmat(mu(:,j),1,length(head_threshold))...
                                   ,1./sqrt(repmat(phi(:,j),1,length(head_threshold))));           
            tail_prob = tail_prob+repmat(omega(:,j),1,length(tail_threshold)).*...
                        (1-normcdf(repmat(tail_threshold,iter,1)...
                                  ,repmat(mu(:,j),1,length(tail_threshold))...
                                  ,1./sqrt(repmat(phi(:,j),1,length(tail_threshold)))));           
            average = average+omega(:,j).*mu(:,j);
        end 
        omega(:,n_cluster) = 1-sum(omega(:,1:n_cluster-1),2);
        q = q+repmat(omega(:,n_cluster),1,t_length).*...
            normpdf(repmat(t,iter,1),...
                    repmat(mu(:,n_cluster),1,t_length),...
                    1./sqrt(repmat(phi(:,n_cluster),1,t_length)));        
        head_prob = head_prob+repmat(omega(:,end),1,length(head_threshold)).*...
                              normcdf(repmat(head_threshold,iter,1)...
                                     ,repmat(mu(:,end),1,length(head_threshold))...
                                     ,1./sqrt(repmat(phi(:,end),1,length(head_threshold))));       
        tail_prob = tail_prob+repmat(omega(:,end),1,length(tail_threshold)).*...
                              (1-normcdf(repmat(tail_threshold,iter,1)...
                                        ,repmat(mu(:,end),1,length(tail_threshold))...
                                        ,1./sqrt(repmat(phi(:,end),1,length(tail_threshold)))));       
        average = average+omega(:,end).*mu(:,end);              
        NewAirlineOnRoute(i).density = [quantile(q,[0.05,0.5,0.95],1);mean(q,1)];
        if i<=n_airline
            NewAirlineOnRoute(i).airline = airlines(i,1);
        else
            NewAirlineOnRoute(i).airline = AL_label;
        end
        NewAirlineOnRoute(i).y = t;
        NewAirlineOnRoute(i).head_threshold = head_threshold;
        NewAirlineOnRoute(i).head_prob = [quantile(head_prob,[0.05,0.5,0.95],1);mean(head_prob,1)];
        NewAirlineOnRoute(i).head_perc = head_perc;
        NewAirlineOnRoute(i).tail_threshold = tail_threshold;
        NewAirlineOnRoute(i).tail_prob = [quantile(tail_prob,[0.05,0.5,0.95],1);mean(tail_prob,1)];
        NewAirlineOnRoute(i).tail_perc = tail_perc;
        NewAirlineOnRoute(i).average = [quantile(average,[0.05,0.5,0.95]),mean(average)];
    end
end
