function Cdf = Predict_Cdf(data_info, predict_info, thinned_sampler, axis)
% only calculate one predict conditional density funciton    
% the index put in this function must be the right indexes
omega = Predict_Omega(data_info, predict_info, thinned_sampler); 
Cdf = repmat(omega(:,1),1,length(axis)).* normcdf(repmat(axis,size(omega,1),1)...
               ,repmat(thinned_sampler.mu(:,1),1,length(axis))...
               ,1./sqrt(repmat(thinned_sampler.phi(:,1),1,length(axis))));
for j=2:size(omega,2)
    Cdf = Cdf+repmat(omega(:,j),1,length(axis))...
             .*normcdf(repmat(axis,size(omega,1),1),repmat(thinned_sampler.mu(:,j),...
             1,length(axis)),1./sqrt(repmat(thinned_sampler.phi(:,j),1,length(axis))));
end
