function prior = PSBP_Prior(data_info, n_cluster)
% This is a function to generate a prior struct based on two inputs.
% 1. data_info contains (1)dependent variable, (2)categorical variable, (3)continuous
% variable and (4)categorical-continuous variable
% 2. n_cluster is the finite cluster number of PSBP mixture model
    % dep ~ \sum omega_i * N(mu, phi), 
    %     , where alpha_i ~ (level_i + \sum categorical + continuous* ..., 1)
        % level_i ~ N(0, xi_level)
        % categorical ~ N(0, xi(:))
            % xi(:), xi_level ~ G(xi_a=6, xi_s=0.2)
        % continuous ~ N(0, 1)
        % phi ~ G(phi_a=1.25, phi_s=0.026)
    prior = struct('phi_a', 1.25, ...
                   'phi_s', 0.021, ...
                   'mu_nu', mean( data_info.dep) * ones(1, n_cluster),...
                   'mu_xi', 2/range( data_info.dep ),...                    
                   'category_nu', zeros(1, sum(max ( data_info.category_predictor, [], 1 ) ) ),... 
                   'category_xi_a', 6, ...
                   'category_xi_s', 0.3,...
                   'continuous_nu', zeros(1, size(data_info.continuous_predictor, 2)),...
                   'continuous_xi', 1,...
                   'level_nu', norminv(1 ./ (1 + n_cluster-(1: n_cluster-1))), ...
                   'level_xi_a', 6, ...
                   'level_xi_s', 0.2);
    %
end